{
 "title": "Glowroot Exporter Dashboard New",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(glowroot_agent_rollup,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(glowroot_agent_rollup{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "AgentRollupDisplayName",
    "label": "AgentRollupDisplayName",
    "query": {
     "query": "label_values(glowroot_agent_rollup{job=~\"$job\", instance=~\"$instance\"},agent_rollup_display_name)"
    }
   },
   {
    "name": "AgentRollupName",
    "label": "AgentRollupName",
    "query": {
     "query": "label_values(glowroot_agent_rollup{job=~\"$job\", instance=~\"$instance\", agent_rollup_display_name=~\"$AgentRollupDisplayName\"},agent_rollup)"
    }
   },
   {
    "name": "AgentId",
    "label": "AgentId",
    "query": {
     "query": "label_values(glowroot_agent_rollup_id{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\"},agent_id)"
    }
   },
   {
    "name": "TraceId",
    "label": "TraceId",
    "query": {
     "query": "label_values(glowroot_points_agent_rollup_id_slow_trace{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"},trace_id)"
    }
   },
   {
    "name": "SlowTraceStatus",
    "label": "SlowTraceStatus",
    "query": {
     "query": "label_values(glowroot_points_agent_rollup_id_slow_trace{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"},status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of  $job ",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (up{job=~\"$job\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Successful $job",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (up{job=~\"$job\"} == 1) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful $job",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 14, "x": 10, "y": 1 },
     "targets": [
      {
       "expr": "count (up{job=~\"$job\"} == 1)  by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Failed $job",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{job=~\"$job\"}== 0) or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed $job ",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 14, "x": 10, "y": 5 },
     "targets": [
      {
       "expr": "count (up{job=~\"$job\"} == 0)  by (instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Glowroot Total Error Count by Agent Rollup",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (glowroot_summaries_agent_rollup_id_error_total_count{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}) by(agent_rollup)",
       "legendFormat": "{{agent_rollup}}"
      }
     ]
    },
    {
     "title": "Glowroot Total Error Count by Agent ID",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "glowroot_summaries_agent_rollup_id_error_total_count{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}",
       "legendFormat": "{{agent_id}}"
      }
     ]
    },
    {
     "title": "Glowroot Total Error Count by Agent Rollup",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum (glowroot_summaries_agent_rollup_id_error_total_count{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}) by(agent_rollup)",
       "legendFormat": "{{agent_rollup}} "
      }
     ]
    },
    {
     "title": "Glowroot Total Error Count by Agent ID",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "glowroot_summaries_agent_rollup_id_error_total_count{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}",
       "legendFormat": "{{agent_id}} "
      }
     ]
    },
    {
     "title": "Glowroot Error Count by Agent ID and Transaction Name",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "glowroot_summaries_agent_rollup_id_error{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}",
       "legendFormat": "{{agent_id}} {{transaction_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Transaction Total ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Glowroot Total Error Transaction Count by Agent Rollup ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (glowroot_summaries_agent_rollup_id_error_transaction_total_count{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}) by(agent_rollup)",
       "legendFormat": "{{agent_rollup}}"
      }
     ]
    },
    {
     "title": "Glowroot Total Error Transaction Count by Agent ID",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "glowroot_summaries_agent_rollup_id_error_transaction_total_count{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}",
       "legendFormat": "{{agent_id}}"
      }
     ]
    },
    {
     "title": "Glowroot Total Error Transaction Count by Agent Rollup",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum (glowroot_summaries_agent_rollup_id_error_transaction_total_count{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}) by(agent_rollup)",
       "legendFormat": "{{agent_id}}"
      }
     ]
    },
    {
     "title": "Glowroot Total Error Transaction Count by Agent ID",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "glowroot_summaries_agent_rollup_id_error_transaction_total_count{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}",
       "legendFormat": "{{agent_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Slow Transactions ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Glowroot Trace Count Agent Rollup Slow Trace",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (glowroot_trace_count_agent_rollup_id_slow_trace{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}) by (agent_rollup)",
       "legendFormat": "{{agent_id}} {{agent_rollup}}"
      }
     ]
    },
    {
     "title": "Glowroot Trace Count Agent Rollup Id Slow Trace",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (glowroot_trace_count_agent_rollup_id_slow_trace{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}) by (agent_rollup,agent_id)",
       "legendFormat": "{{agent_id}}"
      }
     ]
    },
    {
     "title": "Glowroot Trace Count Agent Rollup Slow Trace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum (glowroot_trace_count_agent_rollup_id_slow_trace{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}) by (agent_rollup)",
       "legendFormat": "{{agent_rollup}}"
      }
     ]
    },
    {
     "title": "Glowroot Trace Count Agent Rollup Id Slow Trace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "glowroot_trace_count_agent_rollup_id_slow_trace{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\"}",
       "legendFormat": "{{agent_id}} {{agent_rollup}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Slow Transactions Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Glowroot Points Agent Rollup Slow Trace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(status, agent_id, trace_id) (glowroot_points_agent_rollup_id_slow_trace{job=~\"$job\", instance=~\"$instance\", agent_rollup=~\"$AgentRollupName\", agent_id=~\"$AgentId\", trace_id=~\"$TraceId\", status=~\"$SlowTraceStatus\"})",
       "legendFormat": "{{status}} {{agent_id}} {{trace_id}}"
      }
     ]
    }
   ]
  }
 ]
}